#pragma once
#include "abc_datatype.h" 
struct cpu_x86 {
    Bool Vendor_AMD;
    Bool Vendor_Intel;
    Bool OS_x64;
    Bool OS_AVX;
    Bool OS_AVX512;
    Bool HW_MMX;
    Bool HW_x64;
    Bool HW_ABM;
    Bool HW_RDRAND;
    Bool HW_RDSEED;
    Bool HW_BMI1;
    Bool HW_BMI2;
    Bool HW_ADX;
    Bool HW_MPX;
    Bool HW_PREFETCHW;
    Bool HW_PREFETCHWT1;
    Bool HW_RDPID;
    Bool HW_SSE;
    Bool HW_SSE2;
    Bool HW_SSE3;
    Bool HW_SSSE3;
    Bool HW_SSE41;
    Bool HW_SSE42;
    Bool HW_SSE4a;
    Bool HW_AES;
    Bool HW_SHA;
    Bool HW_AVX;
    Bool HW_XOP;
    Bool HW_FMA3;
    Bool HW_FMA4;
    Bool HW_AVX2;
    Bool HW_AVX512_F;
    Bool HW_AVX512_CD;
    Bool HW_AVX512_PF;
    Bool HW_AVX512_ER;
    Bool HW_AVX512_VL;
    Bool HW_AVX512_BW;
    Bool HW_AVX512_DQ;
    Bool HW_AVX512_IFMA;
    Bool HW_AVX512_VBMI;
    Bool HW_AVX512_VPOPCNTDQ;
    Bool HW_AVX512_4FMAPS;
    Bool HW_AVX512_4VNNIW;
    Bool HW_AVX512_VNNI;
    Bool HW_AVX512_BF16;
    Bool HW_AVX512_VBMI2;
    Bool HW_GFNI;
    Bool HW_VAES;
    Bool HW_AVX512_VPCLMUL;
    Bool HW_AVX512_BITALG;
};
extern void detect_print_cpu(void);
extern void detect_host(struct cpu_x86* cpu);
extern void i386_cpuid_caches(Bool quiet);
extern void print_cpuinfo(struct cpu_x86* cpu);
